import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import QueryProvider from "@/components/query-provider";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body suppressHydrationWarning className={inter.className}>
                <QueryProvider>
                    <ThemeProvider attribute="class" defaultTheme="dark">
                        <main className="max-w-6xl min-h-screen mx-auto py-10 space-y-10">
                            <Navbar />
                            {children}
                        </main>
                        <Toaster />
                    </ThemeProvider>
                    <ReactQueryDevtools/>
                </QueryProvider>
            </body>
        </html>
    );
}
